name: Compile Basalt

on:
  push:
    branches:
      - main
      - dev

jobs:
  windows:
    name: Compile on Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1.4.1
    - name: compile
      shell: cmd
      run: | 
        call windows_modern_build.bat

  ubuntu:
    name: Compile on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compile
        run: |
          make build
