name: Build

on:
  push:
    branches:
      - main
      - windows
  pull_request:
    branches:
      - main
      - windows

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build app for release
        run: msbuild basalt.sln -t:rebuild -verbosity:diag -property:Configuration=Release
