name: Compile Basalt

on:
  push:
    branches:
      - main
      - dev

jobs:
#  windows:
#    name: Compile on Windows
#    runs-on: windows-latest
#    steps:
#    - name: Checkout the repo
#    - uses: actions/checkout@v2
#    - uses: ilammy/msvc-dev-cmd@v1.4.1
#    - name: Install D compiler
#      uses: dlang-community/setup-dlang@v1
#    - name: compile
#      shell: cmd
#      run: | 
#        call windows_modern_build.bat

  ubuntu:
    name: Compile on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
      - uses: actions/checkout@v2
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
      - name: compile
        run: |
          make build