name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build app for debug
        run: msbuild -t:rebuild -property:Configuration=Debug
      - name: Build app for release
        run: msbuild -t:rebuild -property:Configuration=Release
